apiVersion: apps/v1
kind: Deployment
metadata:
  name: historyservice
  labels:
    app: historyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: historyservice
  template:
    metadata:
      labels:
        app: historyservice
    spec:
      containers:
        - name: historyservice
          image: "jypking/historyservice:20240924"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"            
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5